# configs/training_config.yaml
# MultiTalk Training Configuration

# Model Configuration
model_name: "multitalk-14B"
checkpoint_dir: "./pretrained_checkpoints"

# Training Configuration
batch_size: 2
learning_rate: 1e-4
num_epochs: 100
gradient_accumulation_steps: 8
max_grad_norm: 1.0
warmup_steps: 1000

# Data Configuration
data_root: "./data"
json_file: "train_data.json"
image_size: [640, 640]  # [height, width]
frame_num: 81
max_frames: 1000

# Audio Configuration
audio_window: 5
vae_scale: 4

# Output and Logging
output_dir: "./outputs"
logging_steps: 10
save_steps: 1000
eval_steps: 500

# Resume Training
resume_from_checkpoint: null

# Mixed Precision
mixed_precision: "fp16"  # fp16, bf16, no

# DeepSpeed Configuration
use_deepspeed: false
deepspeed_config: null

---
# configs/deepspeed_config.json
{
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 16,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
    }
  },
  "scheduler": {
    "type": "WarmupLR",
    "params": {
      "warmup_min_lr": "auto",
      "warmup_max_lr": "auto",
      "warmup_num_steps": "auto"
    }
  },
  "zero_optimization": {
    "stage": 2,
    "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
    },
    "offload_param": {
      "device": "cpu",
      "pin_memory": true
    },
    "allgather_partitions": true,
    "allgather_bucket_size": 2e8,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 2e8,
    "contiguous_gradients": true
  },
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "steps_per_print": 2000,
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "wall_clock_breakdown": false
}

---
# Example data structure for train_data.json
# [
#   {
#     "prompt": "A man and a woman having a conversation in a living room",
#     "cond_image": "images/conversation_001.jpg",
#     "audio_type": "add",
#     "cond_audio": {
#       "person1": "audio_embeddings/conversation_001_person1.pt",
#       "person2": "audio_embeddings/conversation_001_person2.pt"
#     },
#     "bbox": {
#       "person1": [160, 120, 1280, 1080],
#       "person2": [160, 1320, 1280, 2280]
#     }
#   }
# ]
